apiVersion: v1
kind: Service
metadata:
  name: {{ include "#TEMPLATE_NAME#.fullname" . }}
  labels:
    {{- include "#TEMPLATE_NAME#.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.healthPort }}
      targetPort: 8778
      protocol: TCP
      name: health
  selector:
    {{- include "#TEMPLATE_NAME#.selectorLabels" . | nindent 4 }}
